name: 1.0$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPublish: 'WebApi'
  PublishPath: '$(Build.ArtifactStagingDirectory)/App'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishAsArtifact'
  displayName: 'Build and save zipped Artifact'
  pool:
    name: 'Hosted VS2017'
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      buildConfiguration: $(BuildConfiguration)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Create_SQL_Script.yaml@ALMStuff
    parameters:
      RelativeFolderPath: 'Sources\WebApi'
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Publish.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      FolderToPublish: $(FolderToPublish)
      PublishPath: $(PublishPath)
  - task: PublishBuildArtifacts@1
    displayName: 'Save Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'